### ISSUE TITLE
I have question

### ISSUE THREAD

**Issue by fallsdevil** [T8RIN/ESearch#2]
Hello, I'm using this app and I'm enjoying it and my question is if it's possible to configure a personalized translation, for example translating the page from English to Portuguese, because I tried to change it but it's everything is in Russian and I can't change it, or the option to identify the language of the page and translate it into the desired language

**Comment by T8RIN** [comment]
It is possible but i have created this as study project and now can't support it properly because it have really bad code

**Comment by fallsdevil** [comment]
got it, got an alternative by changing his URL address and it worked, thanks for the answer.
