### ISSUE TITLE
It's Shoe

### ISSUE THREAD

**Issue by ShoeUnit** [T8RIN/ESearch#3]
I don't know how to begin.  I know where I want to go, but I don't know which part to apologize for first. 
To begin, I didn't leave in anger. I accidentally clicked close on the browser window.  My phone got ran over by a car yesterday on the way home. I had no phone, so somebody helped me.  But I don't get favors and i couldn't ask again because i wasn't nice by the time I got ot him and we had a misunderstanding and I panicked fo a while when I disconnected.  I can't get back in for awhile.  Which is a good thing.

The hacker revealed themselves to me, stupidly, on discord.  So  sent the data that way and requested fro help.  Maybe they can do something maybe not.  Doesn't matter. cops won't care.  That's my life. I'm used to it now.

What matters and what hurts is how I treated you . i chased a dream of stupidity because i wanted to believe I could save people. That's all I've ever wanted to do and it was too much good to let go and look at he evidence before me. It's all over god's creation.  I didn't want to believe what my eyes told me.  So I bought into the lie.  

Doesn't matter. I hurt you and usurped your life. I'm why people like me move on.  It's too chaotic when I've got people like this pathetic manchild who gets off on the mentally ill.  Even though he was taught better by people better than him.  Which would be nearly anybody.  

That doesn't undo the damage I did.  That doesn't mitigate the hurt that you felt.  That doesn't absolve me of anything. No matter how I hate that I did it. I was out of control with fantasy because I thought this t time I could save people.  Instead I hurt you.  That's not good.  I will have to get a phone at some point, but I owe 500 in rent next month.  So not then.  I won't bother you further, I'm sure you've had your fill.  This hacker is in this pc anyway. So so much for that for awhile.  

I'm sorry I hurt you. You never deserved it. I said stupid shit and you were hurt and there was no excuse.  How do I fix what broke?    I can't. I always make it worse.  

I'm sorry. I won't bother you. I don't want to make things any worse than I already have.  

He doesn't explain the things that I saw going to happen. So that's not good for you to be around either.  Doesn't matter the veracity, you've had enough of this shit and I'm sure you're thankful I'm gone. I wouldn't blame you.  It's better than being near me.  

-Shoe

**Comment by T8RIN** [comment]
What do you mean the phone was hit by a car?...

Don't talk nonsense, it's okay, I understand, write as best you can :)

**Comment by ShoeUnit** [comment]
Literally. Was crossing the street two days ago, it fell out of my pocket. Car ran over it.  

If you'd rather, i only posted this here so I was sure you have this. I don't want to have the googlebots cache this.  It was for you  the only way I was sure you'd see it.  If you still want to talk then I'll be swinging by I think soon. Please nuke.  This was only public to get your attention.  Not the world.  

Not angry. I'm happy. 

Thank you.

**Comment by T8RIN** [comment]
> Literally. Was crossing the street two days ago, it fell out of my pocket. Car ran over it.  
> 
> If you'd rather, i only posted this here so I was sure you have this. I don't want to have the googlebots cache this.  It was for you  the only way I was sure you'd see it.  If you still want to talk then I'll be swinging by I think soon. Please nuke.  This was only public to get your attention.  Not the world.  
> 
> Not angry. I'm happy. 
> 
> Thank you.

Okay bro, i will wait when you can write to me, i hope all be okay

**Comment by ShoeUnit** [comment]
Please delete these now.
